web:
  build: .
  ports:
    - "8000:80"
    - "8002:9000"
  links:
    - db
    - memcache
  volumes:
    - webroot:/srv/www
    - uploads:/srv/www/uploads
  environment:
    SITE_URL: http://localhost:8000
    WP_DEBUG: 1
  command: supervisord -e debug
db:
  image: orchardup/mysql
  ports:
    - "8001:3306"
  environment:
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
memcache:
  image: octohost/memcached
  command: memcached -m 128 -u daemon -l 0.0.0.0 -v
  expose:
    - "11211"
